sylius_twig_hooks:
    hooks:
        'sylius_admin.workspace.update.content.header':
            breadcrumbs:
                template: '@SyneriseSyliusIntegrationPlugin/admin/shared/crud/update/content/header/breadcrumbs.html.twig'
                priority: 0
        'sylius_admin.workspace.update.content':
            form:
                component: 'synerise_integration:workspace:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusAdmin/shared/crud/common/content/form.html.twig'
                priority: 0
                configuration:
                    method: 'PUT'
        'sylius_admin.workspace.update.content.form':
            sections:
                template: '@SyneriseSyliusIntegrationPlugin/admin/shared/form/sections.html.twig'
        'sylius_admin.workspace.update.content.form.sections':
            general:
                template: '@SyneriseSyliusIntegrationPlugin/admin/workspace/form/sections/general.html.twig'
                priority: 400
            advanced:
                template: '@SyneriseSyliusIntegrationPlugin/admin/workspace/form/sections/advanced.html.twig'
                priority: 300
        'sylius_admin.workspace.update#javascripts':
            custom_scripts:
                template: '@SyneriseSyliusIntegrationPlugin/admin/shared/scripts/popover.html.twig'
                priority: -100
