sylius_twig_hooks:
    hooks:
        'sylius_admin.synchronization_configuration.update.content':
            form:
                component: 'synerise_integration:synchronization_configuration:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusAdmin/shared/crud/common/content/form.html.twig'
                priority: 0
                configuration:
                    method: 'PUT'
        'sylius_admin.synchronization_configuration.update.content.form':
            sections:
                template: '@SyliusAdmin/shared/crud/common/content/form/sections.html.twig'
                priority: 0
        
        'sylius_admin.synchronization_configuration.update.content.form.sections':
            general:
                template: '@SyneriseSyliusIntegrationPlugin/admin/synchronization_configuration/form/sections/general.html.twig'
                priority: 400
            product:
                template: '@SyneriseSyliusIntegrationPlugin/admin/synchronization_configuration/form/sections/product.html.twig'
                priority: 300
        'sylius_admin.synchronization_configuration.update.content.form.sections.general':
            default:
                enabled: false
            channel:
                template: '@SyneriseSyliusIntegrationPlugin/admin/synchronization_configuration/form/sections/general/channel.html.twig'
                priority: 1200
            workspace:
                template: '@SyneriseSyliusIntegrationPlugin/admin/synchronization_configuration/form/sections/general/form_types.html.twig'
                priority: 1100
        'sylius_admin.synchronization_configuration.update.content.form.sections.product':
            product_attributes:
                template: '@SyneriseSyliusIntegrationPlugin/admin/synchronization_configuration/form/sections/general/product_attributes.html.twig'
                priority: 1000
