sylius_twig_hooks:
    hooks:
        'sylius_admin.channel_configuration.update.content.header':
            breadcrumbs:
                template: '@SyneriseSyliusIntegrationPlugin/admin/shared/crud/update/content/header/breadcrumbs.html.twig'
                priority: 0
            
        'sylius_admin.channel_configuration.update.content.header.title_block':
            actions:
                enabled: false
            title:
                template: '@SyneriseSyliusIntegrationPlugin/admin/channel_configuration/update/content/header/title_block/title.html.twig'
        'sylius_admin.channel_configuration.update.content':
            form:
                component: 'synerise_integration:channel_configuration:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusAdmin/shared/crud/common/content/form.html.twig'
                priority: 0
                configuration:
                    method: 'PATCH'
        'sylius_admin.channel_configuration.update.content.form':
            sections:
                template: '@SyneriseSyliusIntegrationPlugin/admin/channel_configuration/form/sections.html.twig'
        'sylius_admin.channel_configuration.update.content.form.sections':
            general:
                template: '@SyneriseSyliusIntegrationPlugin/admin/channel_configuration/form/sections/general.html.twig'
                priority: 400
            tracking:
                template: '@SyneriseSyliusIntegrationPlugin/admin/channel_configuration/form/sections/tracking.html.twig'
                priority: 300
            events:
                template: '@SyneriseSyliusIntegrationPlugin/admin/channel_configuration/form/sections/events.html.twig'
                priority: 200
