sylius_twig_hooks:
    hooks:
        'sylius_admin.base#stylesheets':
            custom_styles:
                template: '@SyneriseSyliusIntegrationPlugin/admin/shared/layout/base/styles.html.twig'
                priority: -100

        'sylius_admin.base#javascripts':
            custom_scripts:
                template: '@SyneriseSyliusIntegrationPlugin/admin/shared/layout/base/scripts.html.twig'
                priority: -100
