sylius_twig_hooks:
    hooks:
        'sylius_shop.base#stylesheets':
            custom_styles:
                template: '@SyneriseSyliusIntegrationPlugin/shop/shared/layout/base/styles.html.twig'
                priority: -100

        'sylius_shop.base#javascripts':
            custom_scripts:
                template: '@SyneriseSyliusIntegrationPlugin/shop/shared/layout/base/scripts.html.twig'
                priority: -100
     
        'sylius_shop.base#metatags':
            open_graph:
                component: synerise_integration:open_graph
                props:
                    product: '@=_context.product'
                    template: '@SyneriseSyliusIntegrationPlugin/shop/shared/layout/base/open_graph.html.twig'
                priority: 100           
