sylius_twig_hooks:
    hooks:
        'sylius_shop.base#stylesheets':
            custom_styles:
                template: '@SyneriseSyliusIntegrationPlugin/shop/shared/layout/base/styles.html.twig'
                priority: -100

        'sylius_shop.base#javascripts':
            custom_scripts:
                template: '@SyneriseSyliusIntegrationPlugin/shop/shared/layout/base/scripts.html.twig'
                priority: -100
            tracking_script:
                component: synerise_integration:tracking_script
                props:
                    template: '@SyneriseSyliusIntegrationPlugin/shop/shared/layout/base/tracking_script.html.twig'
                priority: -100
