framework:
    messenger:
        default_bus: sylius.command_bus
        buses:
            synerise.synchronization_bus:
                middleware:
                    - doctrine_transaction
        routing:
            'Synerise\SyliusIntegrationPlugin\MessageQueue\Message\EventMessage': main
            'Synerise\SyliusIntegrationPlugin\MessageQueue\Message\SyncStartMessage': main
            'Synerise\SyliusIntegrationPlugin\MessageQueue\Message\SyncMessage': main
